# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "JSONStream-1.3.5" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz";
        sha512 = "E+iruNOY8VV9s4JEbe1aNEm6MiszPRr/UfcHMz0TQh1BXSxHK+ASV1R6W4HpjBhSeS+54PIsAMCBmwD06LLsqQ==";
      };
    };
    "acorn-5.7.4" = {
      name = "acorn";
      packageName = "acorn";
      version = "5.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-5.7.4.tgz";
        sha512 = "1D++VG7BhrtvQpNbBzovKNc1FLGGEE/oGe7b9xJm/RFHMBeUaUGpluV9RLjZa47YFdPcDAenEYuq9pQPcMdLJg==";
      };
    };
    "acorn-7.2.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.2.0.tgz";
        sha512 = "apwXVmYVpQ34m/i71vrApRrRKCWQnZZF1+npOD0WV5xZFfwWOmKGQ2RWlfdy9vWITsenisM8M0Qeq8agcFHNiQ==";
      };
    };
    "acorn-node-1.8.2" = {
      name = "acorn-node";
      packageName = "acorn-node";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-node/-/acorn-node-1.8.2.tgz";
        sha512 = "8mt+fslDufLYntIoPAaIMUe/lrbrehIiwmR3t2k9LljIzoigEPF27eLk2hy8zSGzmR/ogr7zbRKINMo1u0yh5A==";
      };
    };
    "acorn-walk-7.1.1" = {
      name = "acorn-walk";
      packageName = "acorn-walk";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-walk/-/acorn-walk-7.1.1.tgz";
        sha512 = "wdlPY2tm/9XBr7QkKlq0WQVgiuGTX6YWPyRyBviSoScBuLfTVQhvwg6wJ369GJ/1nPfTLMfnrFIfjqVg6d+jQQ==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "asn1.js-4.10.1" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-4.10.1.tgz";
        sha512 = "p32cOF5q0Zqs9uBiONKYLm6BClCoBCM5O9JfeUSlnQLBTxYdTK+pW+nXflm8UkKd2UYlEbYz5qEi0JuZR9ckSw==";
      };
    };
    "assert-1.5.0" = {
      name = "assert";
      packageName = "assert";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.5.0.tgz";
        sha512 = "EDsgawzwoun2CZkCgtxJbv392v4nbk9XDD06zI+kQYoBM/3RBWLlEyJARDOmhAAosBjWACEkKL6S+lIZtcAubA==";
      };
    };
    "babel-code-frame-6.26.0" = {
      name = "babel-code-frame";
      packageName = "babel-code-frame";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-code-frame/-/babel-code-frame-6.26.0.tgz";
        sha1 = "63fd43f7dc1e3bb7ce35947db8fe369a3f58c74b";
      };
    };
    "babel-core-6.26.3" = {
      name = "babel-core";
      packageName = "babel-core";
      version = "6.26.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-core/-/babel-core-6.26.3.tgz";
        sha512 = "6jyFLuDmeidKmUEb3NM+/yawG0M2bDZ9Z1qbZP59cyHLz8kYGKYwpJP0UwUKKUiTRNvxfLesJnTedqczP7cTDA==";
      };
    };
    "babel-generator-6.26.1" = {
      name = "babel-generator";
      packageName = "babel-generator";
      version = "6.26.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-generator/-/babel-generator-6.26.1.tgz";
        sha512 = "HyfwY6ApZj7BYTcJURpM5tznulaBvyio7/0d4zFOeMPUmfxkCjHocCuoLa2SAGzBI8AREcH3eP3758F672DppA==";
      };
    };
    "babel-helper-call-delegate-6.24.1" = {
      name = "babel-helper-call-delegate";
      packageName = "babel-helper-call-delegate";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helper-call-delegate/-/babel-helper-call-delegate-6.24.1.tgz";
        sha1 = "ece6aacddc76e41c3461f88bfc575bd0daa2df8d";
      };
    };
    "babel-helper-define-map-6.26.0" = {
      name = "babel-helper-define-map";
      packageName = "babel-helper-define-map";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helper-define-map/-/babel-helper-define-map-6.26.0.tgz";
        sha1 = "a5f56dab41a25f97ecb498c7ebaca9819f95be5f";
      };
    };
    "babel-helper-function-name-6.24.1" = {
      name = "babel-helper-function-name";
      packageName = "babel-helper-function-name";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helper-function-name/-/babel-helper-function-name-6.24.1.tgz";
        sha1 = "d3475b8c03ed98242a25b48351ab18399d3580a9";
      };
    };
    "babel-helper-get-function-arity-6.24.1" = {
      name = "babel-helper-get-function-arity";
      packageName = "babel-helper-get-function-arity";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helper-get-function-arity/-/babel-helper-get-function-arity-6.24.1.tgz";
        sha1 = "8f7782aa93407c41d3aa50908f89b031b1b6853d";
      };
    };
    "babel-helper-hoist-variables-6.24.1" = {
      name = "babel-helper-hoist-variables";
      packageName = "babel-helper-hoist-variables";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helper-hoist-variables/-/babel-helper-hoist-variables-6.24.1.tgz";
        sha1 = "1ecb27689c9d25513eadbc9914a73f5408be7a76";
      };
    };
    "babel-helper-optimise-call-expression-6.24.1" = {
      name = "babel-helper-optimise-call-expression";
      packageName = "babel-helper-optimise-call-expression";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helper-optimise-call-expression/-/babel-helper-optimise-call-expression-6.24.1.tgz";
        sha1 = "f7a13427ba9f73f8f4fa993c54a97882d1244257";
      };
    };
    "babel-helper-regex-6.26.0" = {
      name = "babel-helper-regex";
      packageName = "babel-helper-regex";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helper-regex/-/babel-helper-regex-6.26.0.tgz";
        sha1 = "325c59f902f82f24b74faceed0363954f6495e72";
      };
    };
    "babel-helper-replace-supers-6.24.1" = {
      name = "babel-helper-replace-supers";
      packageName = "babel-helper-replace-supers";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helper-replace-supers/-/babel-helper-replace-supers-6.24.1.tgz";
        sha1 = "bf6dbfe43938d17369a213ca8a8bf74b6a90ab1a";
      };
    };
    "babel-helpers-6.24.1" = {
      name = "babel-helpers";
      packageName = "babel-helpers";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-helpers/-/babel-helpers-6.24.1.tgz";
        sha1 = "3471de9caec388e5c850e597e58a26ddf37602b2";
      };
    };
    "babel-messages-6.23.0" = {
      name = "babel-messages";
      packageName = "babel-messages";
      version = "6.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-messages/-/babel-messages-6.23.0.tgz";
        sha1 = "f3cdf4703858035b2a2951c6ec5edf6c62f2630e";
      };
    };
    "babel-plugin-check-es2015-constants-6.22.0" = {
      name = "babel-plugin-check-es2015-constants";
      packageName = "babel-plugin-check-es2015-constants";
      version = "6.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-check-es2015-constants/-/babel-plugin-check-es2015-constants-6.22.0.tgz";
        sha1 = "35157b101426fd2ffd3da3f75c7d1e91835bbf8a";
      };
    };
    "babel-plugin-transform-es2015-arrow-functions-6.22.0" = {
      name = "babel-plugin-transform-es2015-arrow-functions";
      packageName = "babel-plugin-transform-es2015-arrow-functions";
      version = "6.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-arrow-functions/-/babel-plugin-transform-es2015-arrow-functions-6.22.0.tgz";
        sha1 = "452692cb711d5f79dc7f85e440ce41b9f244d221";
      };
    };
    "babel-plugin-transform-es2015-block-scoped-functions-6.22.0" = {
      name = "babel-plugin-transform-es2015-block-scoped-functions";
      packageName = "babel-plugin-transform-es2015-block-scoped-functions";
      version = "6.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-block-scoped-functions/-/babel-plugin-transform-es2015-block-scoped-functions-6.22.0.tgz";
        sha1 = "bbc51b49f964d70cb8d8e0b94e820246ce3a6141";
      };
    };
    "babel-plugin-transform-es2015-block-scoping-6.26.0" = {
      name = "babel-plugin-transform-es2015-block-scoping";
      packageName = "babel-plugin-transform-es2015-block-scoping";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-block-scoping/-/babel-plugin-transform-es2015-block-scoping-6.26.0.tgz";
        sha1 = "d70f5299c1308d05c12f463813b0a09e73b1895f";
      };
    };
    "babel-plugin-transform-es2015-classes-6.24.1" = {
      name = "babel-plugin-transform-es2015-classes";
      packageName = "babel-plugin-transform-es2015-classes";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-classes/-/babel-plugin-transform-es2015-classes-6.24.1.tgz";
        sha1 = "5a4c58a50c9c9461e564b4b2a3bfabc97a2584db";
      };
    };
    "babel-plugin-transform-es2015-computed-properties-6.24.1" = {
      name = "babel-plugin-transform-es2015-computed-properties";
      packageName = "babel-plugin-transform-es2015-computed-properties";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-computed-properties/-/babel-plugin-transform-es2015-computed-properties-6.24.1.tgz";
        sha1 = "6fe2a8d16895d5634f4cd999b6d3480a308159b3";
      };
    };
    "babel-plugin-transform-es2015-destructuring-6.23.0" = {
      name = "babel-plugin-transform-es2015-destructuring";
      packageName = "babel-plugin-transform-es2015-destructuring";
      version = "6.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-destructuring/-/babel-plugin-transform-es2015-destructuring-6.23.0.tgz";
        sha1 = "997bb1f1ab967f682d2b0876fe358d60e765c56d";
      };
    };
    "babel-plugin-transform-es2015-duplicate-keys-6.24.1" = {
      name = "babel-plugin-transform-es2015-duplicate-keys";
      packageName = "babel-plugin-transform-es2015-duplicate-keys";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-duplicate-keys/-/babel-plugin-transform-es2015-duplicate-keys-6.24.1.tgz";
        sha1 = "73eb3d310ca969e3ef9ec91c53741a6f1576423e";
      };
    };
    "babel-plugin-transform-es2015-for-of-6.23.0" = {
      name = "babel-plugin-transform-es2015-for-of";
      packageName = "babel-plugin-transform-es2015-for-of";
      version = "6.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-for-of/-/babel-plugin-transform-es2015-for-of-6.23.0.tgz";
        sha1 = "f47c95b2b613df1d3ecc2fdb7573623c75248691";
      };
    };
    "babel-plugin-transform-es2015-function-name-6.24.1" = {
      name = "babel-plugin-transform-es2015-function-name";
      packageName = "babel-plugin-transform-es2015-function-name";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-function-name/-/babel-plugin-transform-es2015-function-name-6.24.1.tgz";
        sha1 = "834c89853bc36b1af0f3a4c5dbaa94fd8eacaa8b";
      };
    };
    "babel-plugin-transform-es2015-literals-6.22.0" = {
      name = "babel-plugin-transform-es2015-literals";
      packageName = "babel-plugin-transform-es2015-literals";
      version = "6.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-literals/-/babel-plugin-transform-es2015-literals-6.22.0.tgz";
        sha1 = "4f54a02d6cd66cf915280019a31d31925377ca2e";
      };
    };
    "babel-plugin-transform-es2015-modules-amd-6.24.1" = {
      name = "babel-plugin-transform-es2015-modules-amd";
      packageName = "babel-plugin-transform-es2015-modules-amd";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-modules-amd/-/babel-plugin-transform-es2015-modules-amd-6.24.1.tgz";
        sha1 = "3b3e54017239842d6d19c3011c4bd2f00a00d154";
      };
    };
    "babel-plugin-transform-es2015-modules-commonjs-6.26.2" = {
      name = "babel-plugin-transform-es2015-modules-commonjs";
      packageName = "babel-plugin-transform-es2015-modules-commonjs";
      version = "6.26.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-modules-commonjs/-/babel-plugin-transform-es2015-modules-commonjs-6.26.2.tgz";
        sha512 = "CV9ROOHEdrjcwhIaJNBGMBCodN+1cfkwtM1SbUHmvyy35KGT7fohbpOxkE2uLz1o6odKK2Ck/tz47z+VqQfi9Q==";
      };
    };
    "babel-plugin-transform-es2015-modules-systemjs-6.24.1" = {
      name = "babel-plugin-transform-es2015-modules-systemjs";
      packageName = "babel-plugin-transform-es2015-modules-systemjs";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-modules-systemjs/-/babel-plugin-transform-es2015-modules-systemjs-6.24.1.tgz";
        sha1 = "ff89a142b9119a906195f5f106ecf305d9407d23";
      };
    };
    "babel-plugin-transform-es2015-modules-umd-6.24.1" = {
      name = "babel-plugin-transform-es2015-modules-umd";
      packageName = "babel-plugin-transform-es2015-modules-umd";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-modules-umd/-/babel-plugin-transform-es2015-modules-umd-6.24.1.tgz";
        sha1 = "ac997e6285cd18ed6176adb607d602344ad38468";
      };
    };
    "babel-plugin-transform-es2015-object-super-6.24.1" = {
      name = "babel-plugin-transform-es2015-object-super";
      packageName = "babel-plugin-transform-es2015-object-super";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-object-super/-/babel-plugin-transform-es2015-object-super-6.24.1.tgz";
        sha1 = "24cef69ae21cb83a7f8603dad021f572eb278f8d";
      };
    };
    "babel-plugin-transform-es2015-parameters-6.24.1" = {
      name = "babel-plugin-transform-es2015-parameters";
      packageName = "babel-plugin-transform-es2015-parameters";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-parameters/-/babel-plugin-transform-es2015-parameters-6.24.1.tgz";
        sha1 = "57ac351ab49caf14a97cd13b09f66fdf0a625f2b";
      };
    };
    "babel-plugin-transform-es2015-shorthand-properties-6.24.1" = {
      name = "babel-plugin-transform-es2015-shorthand-properties";
      packageName = "babel-plugin-transform-es2015-shorthand-properties";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-shorthand-properties/-/babel-plugin-transform-es2015-shorthand-properties-6.24.1.tgz";
        sha1 = "24f875d6721c87661bbd99a4622e51f14de38aa0";
      };
    };
    "babel-plugin-transform-es2015-spread-6.22.0" = {
      name = "babel-plugin-transform-es2015-spread";
      packageName = "babel-plugin-transform-es2015-spread";
      version = "6.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-spread/-/babel-plugin-transform-es2015-spread-6.22.0.tgz";
        sha1 = "d6d68a99f89aedc4536c81a542e8dd9f1746f8d1";
      };
    };
    "babel-plugin-transform-es2015-sticky-regex-6.24.1" = {
      name = "babel-plugin-transform-es2015-sticky-regex";
      packageName = "babel-plugin-transform-es2015-sticky-regex";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-sticky-regex/-/babel-plugin-transform-es2015-sticky-regex-6.24.1.tgz";
        sha1 = "00c1cdb1aca71112cdf0cf6126c2ed6b457ccdbc";
      };
    };
    "babel-plugin-transform-es2015-template-literals-6.22.0" = {
      name = "babel-plugin-transform-es2015-template-literals";
      packageName = "babel-plugin-transform-es2015-template-literals";
      version = "6.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-template-literals/-/babel-plugin-transform-es2015-template-literals-6.22.0.tgz";
        sha1 = "a84b3450f7e9f8f1f6839d6d687da84bb1236d8d";
      };
    };
    "babel-plugin-transform-es2015-typeof-symbol-6.23.0" = {
      name = "babel-plugin-transform-es2015-typeof-symbol";
      packageName = "babel-plugin-transform-es2015-typeof-symbol";
      version = "6.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-typeof-symbol/-/babel-plugin-transform-es2015-typeof-symbol-6.23.0.tgz";
        sha1 = "dec09f1cddff94b52ac73d505c84df59dcceb372";
      };
    };
    "babel-plugin-transform-es2015-unicode-regex-6.24.1" = {
      name = "babel-plugin-transform-es2015-unicode-regex";
      packageName = "babel-plugin-transform-es2015-unicode-regex";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-es2015-unicode-regex/-/babel-plugin-transform-es2015-unicode-regex-6.24.1.tgz";
        sha1 = "d38b12f42ea7323f729387f18a7c5ae1faeb35e9";
      };
    };
    "babel-plugin-transform-regenerator-6.26.0" = {
      name = "babel-plugin-transform-regenerator";
      packageName = "babel-plugin-transform-regenerator";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-regenerator/-/babel-plugin-transform-regenerator-6.26.0.tgz";
        sha1 = "e0703696fbde27f0a3efcacf8b4dca2f7b3a8f2f";
      };
    };
    "babel-plugin-transform-strict-mode-6.24.1" = {
      name = "babel-plugin-transform-strict-mode";
      packageName = "babel-plugin-transform-strict-mode";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-transform-strict-mode/-/babel-plugin-transform-strict-mode-6.24.1.tgz";
        sha1 = "d5faf7aa578a65bbe591cf5edae04a0c67020758";
      };
    };
    "babel-preset-es2015-6.24.1" = {
      name = "babel-preset-es2015";
      packageName = "babel-preset-es2015";
      version = "6.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-preset-es2015/-/babel-preset-es2015-6.24.1.tgz";
        sha1 = "d44050d6bc2c9feea702aaf38d727a0210538939";
      };
    };
    "babel-register-6.26.0" = {
      name = "babel-register";
      packageName = "babel-register";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-register/-/babel-register-6.26.0.tgz";
        sha1 = "6ed021173e2fcb486d7acb45c6009a856f647071";
      };
    };
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "babel-template-6.26.0" = {
      name = "babel-template";
      packageName = "babel-template";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-template/-/babel-template-6.26.0.tgz";
        sha1 = "de03e2d16396b069f46dd9fff8521fb1a0e35e02";
      };
    };
    "babel-traverse-6.26.0" = {
      name = "babel-traverse";
      packageName = "babel-traverse";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-traverse/-/babel-traverse-6.26.0.tgz";
        sha1 = "46a9cbd7edcc62c8e5c064e2d2d8d0f4035766ee";
      };
    };
    "babel-types-6.26.0" = {
      name = "babel-types";
      packageName = "babel-types";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-types/-/babel-types-6.26.0.tgz";
        sha1 = "a3b073f94ab49eb6fa55cd65227a334380632497";
      };
    };
    "babelify-7.3.0" = {
      name = "babelify";
      packageName = "babelify";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babelify/-/babelify-7.3.0.tgz";
        sha1 = "aa56aede7067fd7bd549666ee16dc285087e88e5";
      };
    };
    "babylon-6.18.0" = {
      name = "babylon";
      packageName = "babylon";
      version = "6.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babylon/-/babylon-6.18.0.tgz";
        sha512 = "q/UEjfGJ2Cm3oKV71DJz9d25TPnq5rhBVL2Q4fA5wcC3jcrdn7+SssEybFIxwAvvP+YCsCYNKughoF33GxgycQ==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 = "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "bn.js-4.11.9" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.9.tgz";
        sha512 = "E6QoYqCKZfgatHTdHzs1RRKP7ip4vvm+EyRUeE2RF0NblwVvb0p6jSVeNTOFxPn26QXN2o6SMfNxKp6kU8zQaw==";
      };
    };
    "bn.js-5.1.2" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.1.2.tgz";
        sha512 = "40rZaf3bUNKTVYu9sIeeEGOg7g14Yvnj9kH7b50EiwX0Q7A6umbvfI5tvHaOERH0XigqKkfLkFQxzb4e6CIXnA==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha1 = "12c25efe40a45e3c323eb8675a0a0ce57b22371f";
      };
    };
    "browser-pack-6.1.0" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-pack/-/browser-pack-6.1.0.tgz";
        sha512 = "erYug8XoqzU3IfcU8fUgyHqyOXqIE4tUTTQ+7mqUjQlvnXkOO6OlT9c/ZoJVHYoAaqGxr09CN53G7XIsO4KtWA==";
      };
    };
    "browser-resolve-1.11.3" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.11.3.tgz";
        sha512 = "exDi1BYWB/6raKHmDTCicQfTkqwN5fioMFV4j8BsfMU4R2DK/QfZfK7kOVkmWCNANf0snkBzqGqAJBao9gZMdQ==";
      };
    };
    "browserify-13.3.0" = {
      name = "browserify";
      packageName = "browserify";
      version = "13.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify/-/browserify-13.3.0.tgz";
        sha1 = "b5a9c9020243f0c70e4675bec8223bc627e415ce";
      };
    };
    "browserify-aes-1.2.0" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.2.0.tgz";
        sha512 = "+7CHXqGuspUn/Sl5aO7Ea0xWGAtETPXNSAjHo48JfLdPWcMng33Xe4znFvQweqc/uzk5zSOI3H52CYnjCfb5hA==";
      };
    };
    "browserify-cipher-1.0.1" = {
      name = "browserify-cipher";
      packageName = "browserify-cipher";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cipher/-/browserify-cipher-1.0.1.tgz";
        sha512 = "sPhkz0ARKbf4rRQt2hTpAHqn47X3llLkUGn+xEJzLjwY8LRs2p0v7ljvI5EyoRO/mexrNunNECisZs+gw2zz1w==";
      };
    };
    "browserify-des-1.0.2" = {
      name = "browserify-des";
      packageName = "browserify-des";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-des/-/browserify-des-1.0.2.tgz";
        sha512 = "BioO1xf3hFwz4kc6iBhI3ieDFompMhrMlnDFC4/0/vd5MokpuAc3R+LYbwTA9A5Yc9pq9UYPqffKpW2ObuwX5A==";
      };
    };
    "browserify-rsa-4.0.1" = {
      name = "browserify-rsa";
      packageName = "browserify-rsa";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-rsa/-/browserify-rsa-4.0.1.tgz";
        sha1 = "21e0abfaf6f2029cf2fafb133567a701d4135524";
      };
    };
    "browserify-sign-4.2.0" = {
      name = "browserify-sign";
      packageName = "browserify-sign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-sign/-/browserify-sign-4.2.0.tgz";
        sha512 = "hEZC1KEeYuoHRqhGhTy6gWrpJA3ZDjFWv0DE61643ZnOXAKJb3u7yWcrU0mMc9SwAqK1n7myPGndkp0dFG7NFA==";
      };
    };
    "browserify-zlib-0.1.4" = {
      name = "browserify-zlib";
      packageName = "browserify-zlib";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.1.4.tgz";
        sha1 = "bb35f8a519f600e0fa6b8485241c979d0141fb2d";
      };
    };
    "buffer-4.9.2" = {
      name = "buffer";
      packageName = "buffer";
      version = "4.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-4.9.2.tgz";
        sha512 = "xq+q3SRMOxGivLhBNaUdC64hDTQwejJ+H0T/NB1XMtTVEwNTrfFF3gAxiyW0Bu/xWEGhjVKgUcMhCrUy2+uCWg==";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha1 = "26e61ed1422fb70dd42e6e36729ed51d855fe8d9";
      };
    };
    "builtin-status-codes-3.0.0" = {
      name = "builtin-status-codes";
      packageName = "builtin-status-codes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-status-codes/-/builtin-status-codes-3.0.0.tgz";
        sha1 = "85982878e21b98e1c66425e03d0174788f569ee8";
      };
    };
    "cached-path-relative-1.0.2" = {
      name = "cached-path-relative";
      packageName = "cached-path-relative";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cached-path-relative/-/cached-path-relative-1.0.2.tgz";
        sha512 = "5r2GqsoEb4qMTTN9J+WzXfjov+hjxT+j3u5K+kIVNIwAd99DLCJE9pBIMP1qVeybV6JiijL385Oz0DcYxfbOIg==";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "combine-source-map-0.8.0" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.8.0.tgz";
        sha1 = "a58d0df042c186fcf822a8e8015f5450d2d79a8b";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-1.5.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.5.2.tgz";
        sha1 = "708978624d856af41a5a741defdd261da752c266";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "console-browserify-1.2.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.2.0.tgz";
        sha512 = "ZMkYO/LkF17QvCPqM0gxw8yUzigAOZOSWSHg91FH6orS7vcEj5dVZTidN2fQ14yBSdg97RqhSNwLUXInd52OTA==";
      };
    };
    "constants-browserify-1.0.0" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/constants-browserify/-/constants-browserify-1.0.0.tgz";
        sha1 = "c20b96d8c617748aaf1c16021760cd27fcb8cb75";
      };
    };
    "convert-source-map-1.1.3" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.1.3.tgz";
        sha1 = "4829c877e9fe49b3161f3bf3673888e204699860";
      };
    };
    "convert-source-map-1.7.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.7.0.tgz";
        sha512 = "4FJkXzKXEDB1snCFZlLP4gpC3JILicCpGbzG9f9G7tGqGCzETQ2hWPrcinA9oU4wtf2biUaEH5065UnMeR33oA==";
      };
    };
    "core-js-2.6.11" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.6.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.6.11.tgz";
        sha512 = "5wjnpaT/3dV+XB4borEsnAYQchn00XSgTAWKDkEqv+K8KevjbzmofK6hfJ9TZIlpj2N0xQpazy7PiRQiWHqzWg==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "create-ecdh-4.0.3" = {
      name = "create-ecdh";
      packageName = "create-ecdh";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-ecdh/-/create-ecdh-4.0.3.tgz";
        sha512 = "GbEHQPMOswGpKXM9kCWVrremUcBmjteUaQ01T9rkKCPDXfUHX0IoP9LpHYo2NPFampa4e+/pFDc3jQdxrxQLaw==";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 = "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-hmac-1.1.7" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.7.tgz";
        sha512 = "MJG9liiZ+ogc4TzUwuvbER1JRdgvUFSB5+VR/g5h82fGaIRWMWddtKBHi7/sVhfjQZ6SehlyhvQYrcYkaUIpLg==";
      };
    };
    "crypto-browserify-3.12.0" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.12.0.tgz";
        sha512 = "fz4spIh+znjO2VjL+IdhEpRJ3YN6sMzITSBijk6FK2UvTqruSQW+/cCZTSNsMiZNvUeq0CqurF+dAbyiGOY6Wg==";
      };
    };
    "dash-ast-1.0.0" = {
      name = "dash-ast";
      packageName = "dash-ast";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dash-ast/-/dash-ast-1.0.0.tgz";
        sha512 = "Vy4dx7gquTeMcQR/hDkYLGUnwVil6vk4FOOct+djUnHOUWt+zJPJAaRIXaAFkPXtJjvlY7o3rfRu0/3hpnwoUA==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "deps-sort-2.0.1" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-2.0.1.tgz";
        sha512 = "1orqXQr5po+3KI6kQb9A4jnXT1PBwggGl2d7Sq2xsnOeI9GPcE/tGcF9UiSZtZBM7MukY4cAh7MemS6tZYipfw==";
      };
    };
    "des.js-1.0.1" = {
      name = "des.js";
      packageName = "des.js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/des.js/-/des.js-1.0.1.tgz";
        sha512 = "Q0I4pfFrv2VPd34/vfLrFOoRmlYj3OV50i7fskps1jZWK1kApMWWT9G6RRUeYedLcBDIhnSDaUvJMb3AhUlaEA==";
      };
    };
    "detect-indent-4.0.0" = {
      name = "detect-indent";
      packageName = "detect-indent";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-indent/-/detect-indent-4.0.0.tgz";
        sha1 = "f76d064352cdf43a1cb6ce619c4ee3a9475de208";
      };
    };
    "detective-4.7.1" = {
      name = "detective";
      packageName = "detective";
      version = "4.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-4.7.1.tgz";
        sha512 = "H6PmeeUcZloWtdt4DAkFyzFL94arpHr3NOwwmVILFiy+9Qd4JTxxXrzfyGk/lmct2qVGBwTSwSXagqu2BxmWig==";
      };
    };
    "diffie-hellman-5.0.3" = {
      name = "diffie-hellman";
      packageName = "diffie-hellman";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-5.0.3.tgz";
        sha512 = "kqag/Nl+f3GwyK25fhUMYj81BUOrZ9IuJsjIcDE5icNM9FJHAVm3VcUDxdLPoQtTuUylWm6ZIknYJwwaPxsUzg==";
      };
    };
    "domain-browser-1.1.7" = {
      name = "domain-browser";
      packageName = "domain-browser";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/domain-browser/-/domain-browser-1.1.7.tgz";
        sha1 = "867aa4b093faa05f1de08c06f4d7b21fdf8698bc";
      };
    };
    "duplexer2-0.1.4" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.1.4.tgz";
        sha1 = "8b12dab878c0d69e3e7891051662a32fc6bddcc1";
      };
    };
    "elliptic-6.5.2" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.5.2.tgz";
        sha512 = "f4x70okzZbIQl/NSRLkI/+tteV/9WqL98zx+SQ69KbXxmVrmjwsNUPn/gYJJ0sHvEak24cZgHIPegRePAtA/xw==";
      };
    };
    "es-abstract-1.17.5" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.17.5.tgz";
        sha512 = "BR9auzDbySxOcfog0tLECW8l28eRGpDpU3Dm3Hp4q/N+VtLTmyj4EUN088XZWQDW/hzj6sYRDXeOFsaAODKvpg==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "events-1.1.1" = {
      name = "events";
      packageName = "events";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-1.1.1.tgz";
        sha1 = "9ebdb7635ad099c70dcc4c2a1f5004288e8bd924";
      };
    };
    "evp_bytestokey-1.0.3" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.3.tgz";
        sha512 = "/f2Go4TognH/KvCISP7OUsHn85hT9nUkxxA9BEWxFn+Oj9o8ZNLm/40hdlgSLyuOimsrTKLUMEorQexp/aPQeA==";
      };
    };
    "fast-safe-stringify-2.0.7" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.7.tgz";
        sha512 = "Utm6CdzT+6xsDk2m8S6uL8VHxNwI6Jub+e9NYTcAms28T84pTa25GJQV9j0CY0N1rM8hK4x6grpF2BQf+2qwVA==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-assigned-identifiers-1.2.0" = {
      name = "get-assigned-identifiers";
      packageName = "get-assigned-identifiers";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-assigned-identifiers/-/get-assigned-identifiers-1.2.0.tgz";
        sha512 = "mBBwmeGTrxEMO4pMaaf/uUEFHnYtwr8FTe8Y/mer4rcV/bye0qGm6pw1bGZFGStxC5O76c5ZAVBGnqHmOaJpdQ==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "globals-9.18.0" = {
      name = "globals";
      packageName = "globals";
      version = "9.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-9.18.0.tgz";
        sha512 = "S0nG3CLEQiY/ILxqtztTWH/3iRRdyBLw6KMDxnKMchrtbj2OFmehVh0WUCfW3DUrIgx/qFrJPICrq4Z4sTR9UQ==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-symbols-1.0.1" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.1.tgz";
        sha512 = "PLcsoqu++dmEIZB+6totNFKq/7Do+Z0u4oT0zKOJNl3lYK6vGwwu2hjHs+68OEZbTjiUE9bgOABXbP/GvrS0Kg==";
      };
    };
    "hash-base-3.1.0" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.1.0.tgz";
        sha512 = "1nmYp/rhMDiE7AYkDw+lLwlAzz0AntGIe51F3RfFfEqyQ3feY2eI/NcwC6umIQVOASPMsWJLJScWKSSvzL9IVA==";
      };
    };
    "hash.js-1.1.7" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.1.7.tgz";
        sha512 = "taOaskGt4z4SOANNseOviYDvjEJinIkRgmp7LbKP2YTTmVxWBl87s/uzK9r+44BclBSp2X7K1hqeNfz9JbBeXA==";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha1 = "d2745701025a6c775a6c545793ed502fc0c649a1";
      };
    };
    "home-or-tmp-2.0.0" = {
      name = "home-or-tmp";
      packageName = "home-or-tmp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/home-or-tmp/-/home-or-tmp-2.0.0.tgz";
        sha1 = "e36c3f2d2cae7d746a857e38d18d5f32a7882db8";
      };
    };
    "htmlescape-1.1.1" = {
      name = "htmlescape";
      packageName = "htmlescape";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.1.tgz";
        sha1 = "3a03edc2214bca3b66424a3e7959349509cb0351";
      };
    };
    "https-browserify-0.0.1" = {
      name = "https-browserify";
      packageName = "https-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-browserify/-/https-browserify-0.0.1.tgz";
        sha1 = "3f91365cabe60b77ed0ebba24b454e3e09d95a82";
      };
    };
    "ieee754-1.1.13" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz";
        sha512 = "4vf7I2LYV/HaWerSo3XmlMkp5eZ83i+/CDluXi/IGTs/O1sejBNhTtnxzmRZfvOUqj7lZjqHkeTvpgSFDlWZTg==";
      };
    };
    "indexof-0.0.1" = {
      name = "indexof";
      packageName = "indexof";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz";
        sha1 = "82dc336d232b9062179d05ab3293a66059fd435d";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "inline-source-map-0.6.2" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.6.2.tgz";
        sha1 = "f9393471c18a79d1724f863fa38b586370ade2a5";
      };
    };
    "insert-module-globals-7.2.0" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-7.2.0.tgz";
        sha512 = "VE6NlW+WGn2/AeOMd496AHFYmE7eLKkUY6Ty31k4og5vmA3Fjuwe9v6ifH6Xx/Hz27QvdoMoviw1/pqWRB09Sw==";
      };
    };
    "invariant-2.2.4" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
        sha512 = "phJfQVBuaJM5raOpJjSfkiD6BpbCE4Ns//LaXl6wGYtUBY83nWS6Rf9tXm2e8VaK60JEjYldbPif/A2B1C2gNA==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-callable-1.1.5" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.5.tgz";
        sha512 = "ESKv5sMCJB2jnHTWZ3O5itG+O128Hsus4K4Qh1h2/cgn2vbgnLSVqfV46AeJA9D5EeeLa9w81KUXMtn34zhX+Q==";
      };
    };
    "is-date-object-1.0.2" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.2.tgz";
        sha512 = "USlDT524woQ08aoZFzh3/Z6ch9Y/EWXEHQ/AaRN0SkKq4t2Jw2R2339tSXmwuVoY7LLlBCbOIlx2myP/L5zk0g==";
      };
    };
    "is-finite-1.1.0" = {
      name = "is-finite";
      packageName = "is-finite";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-finite/-/is-finite-1.1.0.tgz";
        sha512 = "cdyMtqX/BOqqNBBiKlIVkytNHm49MtMlYyn1zxzvJKWmFMlGzm+ry5BBfYyeY9YmNKbRSo/o7OX9w9ale0wg3w==";
      };
    };
    "is-regex-1.0.5" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.0.5.tgz";
        sha512 = "vlKW17SNq44owv5AQR3Cq0bQPEb8+kF3UKZ2fiZNOWtztYE5i0CzCZxFDwO58qAOWtxdBRVO/V5Qin1wjCqFYQ==";
      };
    };
    "is-symbol-1.0.3" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.3.tgz";
        sha512 = "OwijhaRSgqvhm/0ZdAcXNZt9lYdKFpcRDT5ULUuYXPoT794UNOdU+gpT6Rzo7b4V2HUl/op6GqY894AZwv9faQ==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "js-tokens-3.0.2" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz";
        sha1 = "9866df395102130e38f7f996bceb65443209c25b";
      };
    };
    "jsesc-0.5.0" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-0.5.0.tgz";
        sha1 = "e7dee66e35d6fc16f710fe91d5cf69f70f08911d";
      };
    };
    "jsesc-1.3.0" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-1.3.0.tgz";
        sha1 = "46c3fec8c1892b12b0833db9bc7622176dbab34b";
      };
    };
    "json-stable-stringify-0.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-0.0.1.tgz";
        sha1 = "611c23e814db375527df851193db59dd2af27f45";
      };
    };
    "json5-0.5.1" = {
      name = "json5";
      packageName = "json5";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-0.5.1.tgz";
        sha1 = "1eade7acc012034ad84e2396767ead9fa5495821";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "jsonparse-1.3.1" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.1.tgz";
        sha1 = "3f4dae4a91fac315f71062f8521cc239f1366280";
      };
    };
    "labeled-stream-splicer-2.0.2" = {
      name = "labeled-stream-splicer";
      packageName = "labeled-stream-splicer";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/labeled-stream-splicer/-/labeled-stream-splicer-2.0.2.tgz";
        sha512 = "Ca4LSXFFZUjPScRaqOcFxneA0VpKZr4MMYCljyQr4LIewTLb3Y0IUTIsnBBsVubIeEfxeSZpSjSsRM8APEQaAw==";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 = "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "lodash.memoize-3.0.4" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz";
        sha1 = "2dcbd2c287cbc0a55cc42328bd0c736150d53e3f";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 = "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "miller-rabin-4.0.1" = {
      name = "miller-rabin";
      packageName = "miller-rabin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.1.tgz";
        sha512 = "115fLhvZVqWwHPbClyntxEVfVDfl9DLLTuJvq3g2O/Oxi8AiNouAHvDSzHS0viUJc+V5vm3eq91Xwqn9dp4jRA==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 = "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha1 = "f6c00c1c0b082246e5c4d99dfb8c7c083b2b582a";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "mkdirp-0.5.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz";
        sha512 = "NKmAlESf6jMGym1++R0Ra7wvhV+wFW63FaSOFPwRahvea0gMUcGUhVeAg/0BC0wiv9ih5NYPB1Wn1UEI1/L+xQ==";
      };
    };
    "module-deps-4.1.1" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-4.1.1.tgz";
        sha1 = "23215833f1da13fd606ccb8087b44852dcb821fd";
      };
    };
    "moment-2.26.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.26.0.tgz";
        sha512 = "oIixUO+OamkUkwjhAVE18rAMfRJNsNe/Stid/gwHSOfHrOtw9EhAY2AHvdKZ/k/MggcYELFCJz/Sn2pL8b8JMw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-inspect-1.7.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.7.0.tgz";
        sha512 = "a7pEHdh1xKIAgTySUGgLMx/xwDZskN1Ud6egYYN3EdRW4ZMPNEDUTF+hwy2LUC+Bl+SyLXANnwz/jyh/qutKUw==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.0" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.0.tgz";
        sha512 = "exHJeq6kBKj58mqGyTQ9DFvrZC/eR6OwxzoM9YRoGBqrXYonaFyGiFMuc9VZrXf7DarreEwMpurG3dd+CNyW5w==";
      };
    };
    "object.entries-1.1.2" = {
      name = "object.entries";
      packageName = "object.entries";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.entries/-/object.entries-1.1.2.tgz";
        sha512 = "BQdB9qKmb/HyNdMNWVr7O3+z5MUIx3aiegEIJqjMBbBf0YT9RRxTJSim4mzFqtyr7PDAHigq0N9dO0m0tRakQA==";
      };
    };
    "object.values-1.1.1" = {
      name = "object.values";
      packageName = "object.values";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.values/-/object.values-1.1.1.tgz";
        sha512 = "WTa54g2K8iu0kmS/us18jEmdv1a4Wi//BZ/DTVYEcH0XhLM5NYdpDHja3gt57VrZLcNAO2WGA+KpWsDBaHt6eA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "os-browserify-0.1.2" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-browserify/-/os-browserify-0.1.2.tgz";
        sha1 = "49ca0293e0b19590a5f5de10c7f265a617d8fe54";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "pako-0.2.9" = {
      name = "pako";
      packageName = "pako";
      version = "0.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-0.2.9.tgz";
        sha1 = "f3f7522f4ef782348da8161bad9ecfd51bf83a75";
      };
    };
    "parents-1.0.1" = {
      name = "parents";
      packageName = "parents";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-1.0.1.tgz";
        sha1 = "fedd4d2bf193a77745fe71e371d73c3307d9c751";
      };
    };
    "parse-asn1-5.1.5" = {
      name = "parse-asn1";
      packageName = "parse-asn1";
      version = "5.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-asn1/-/parse-asn1-5.1.5.tgz";
        sha512 = "jkMYn1dcJqF6d5CpU689bq7w/b5ALS9ROVSpQDPrZsqqesUJii9qutvoT5ltGedNXMO2e16YUWIghG9KxaViTQ==";
      };
    };
    "path-browserify-0.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.1.tgz";
        sha512 = "BapA40NHICOS+USX9SN4tyhq+A2RrN/Ws5F0Z5aMHDp98Fl86lX8Oti8B7uN93L4Ifv4fHOEA+pQw87gmMO/lQ==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-platform-0.11.15" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.11.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-platform/-/path-platform-0.11.15.tgz";
        sha1 = "e864217f74c36850f0852b78dc7bf7d4a5721bf2";
      };
    };
    "pbkdf2-3.0.17" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.0.17.tgz";
        sha512 = "U/il5MsrZp7mGg3mSQfn742na2T+1/vHDCG5/iTI3X9MKUuYUZVLQhyRsg06mCgDBTd57TxzgZt7P+fYfjRLtA==";
      };
    };
    "private-0.1.8" = {
      name = "private";
      packageName = "private";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/private/-/private-0.1.8.tgz";
        sha512 = "VvivMrbvd2nKkiG38qjULzlc+4Vx4wm/whI9pQD35YrARNnhxeiRktSOhSukRLFNlzg6Br/cJPet5J/u19r/mg==";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "public-encrypt-4.0.3" = {
      name = "public-encrypt";
      packageName = "public-encrypt";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/public-encrypt/-/public-encrypt-4.0.3.tgz";
        sha512 = "zVpa8oKZSz5bTMTFClc1fQOnyyEzpl5ozpi1B5YcvBrdohMjH2rfsBtyXcuNuwjsDIXmBYlF2N5FlJYhR29t8Q==";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "querystring-es3-0.2.1" = {
      name = "querystring-es3";
      packageName = "querystring-es3";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz";
        sha1 = "9ec61f79049875707d69414596fd907a4d711e73";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "randomfill-1.0.4" = {
      name = "randomfill";
      packageName = "randomfill";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomfill/-/randomfill-1.0.4.tgz";
        sha512 = "87lcbR8+MhcWcUiQ+9e+Rwx8MyR2P7qnt15ynUlbm3TU/fjbgz4GsvfSUDTemtCCtVCqb4ZcEFlyPNTh9bBTLw==";
      };
    };
    "read-only-stream-2.0.0" = {
      name = "read-only-stream";
      packageName = "read-only-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-only-stream/-/read-only-stream-2.0.0.tgz";
        sha1 = "2724fd6a8113d73764ac288d4386270c1dbf17f0";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "regenerate-1.4.0" = {
      name = "regenerate";
      packageName = "regenerate";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerate/-/regenerate-1.4.0.tgz";
        sha512 = "1G6jJVDWrt0rK99kBjvEtziZNCICAuvIPkSiUFIQxVP06RCVpq3dmDo2oi6ABpYaDYaTRr67BEhL8r1wgEZZKg==";
      };
    };
    "regenerator-runtime-0.11.1" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz";
        sha512 = "MguG95oij0fC3QV3URf4V2SDYGJhJnJGqvIIgdECeODCT98wSWDAJ94SSuVpYQUoTcGUIL6L4yNB7j1DFFHSBg==";
      };
    };
    "regenerator-transform-0.10.1" = {
      name = "regenerator-transform";
      packageName = "regenerator-transform";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-transform/-/regenerator-transform-0.10.1.tgz";
        sha512 = "PJepbvDbuK1xgIgnau7Y90cwaAmO/LCLMI2mPvaXq2heGMR3aWW5/BQvYrhJ8jgmQjXewXvBjzfqKcVOmhjZ6Q==";
      };
    };
    "regexpu-core-2.0.0" = {
      name = "regexpu-core";
      packageName = "regexpu-core";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexpu-core/-/regexpu-core-2.0.0.tgz";
        sha1 = "49d038837b8dcf8bfa5b9a42139938e6ea2ae240";
      };
    };
    "regjsgen-0.2.0" = {
      name = "regjsgen";
      packageName = "regjsgen";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regjsgen/-/regjsgen-0.2.0.tgz";
        sha1 = "6c016adeac554f75823fe37ac05b92d5a4edb1f7";
      };
    };
    "regjsparser-0.1.5" = {
      name = "regjsparser";
      packageName = "regjsparser";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/regjsparser/-/regjsparser-0.1.5.tgz";
        sha1 = "7ee8f84dc6fa792d3fd0ae228d24bd949ead205c";
      };
    };
    "repeating-2.0.1" = {
      name = "repeating";
      packageName = "repeating";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeating/-/repeating-2.0.1.tgz";
        sha1 = "5214c53a926d3552707527fbab415dbc08d06dda";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "resolve-1.17.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.17.0.tgz";
        sha512 = "ic+7JYiV8Vi2yzQGFWOkiZD5Z9z7O2Zhm9XMaTxdJExKasieFCr+yXZ/WmXsckHiKl12ar0y6XiXDx3m4RHn1w==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 = "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "shasum-1.0.2" = {
      name = "shasum";
      packageName = "shasum";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum/-/shasum-1.0.2.tgz";
        sha1 = "e7012310d8f417f4deb5712150e5678b87ae565f";
      };
    };
    "shasum-object-1.0.0" = {
      name = "shasum-object";
      packageName = "shasum-object";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum-object/-/shasum-object-1.0.0.tgz";
        sha512 = "Iqo5rp/3xVi6M4YheapzZhhGPVs0yZwHj7wvwQ1B9z8H6zk+FEnI7y3Teq7qwnekfEhu8WmG2z0z4iWZaxLWVg==";
      };
    };
    "shell-quote-1.7.2" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.7.2.tgz";
        sha512 = "mRz/m/JVscCrkMyPqHc/bczi3OQHkLTqXHEFu0zDhK/qfv3UcOA4SVmRCLmos4bhjr9ekVQubj/R7waKapmiQg==";
      };
    };
    "simple-concat-1.0.0" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.0.tgz";
        sha1 = "7344cbb8b6e26fb27d66b2fc86f9f6d5997521c6";
      };
    };
    "slash-1.0.0" = {
      name = "slash";
      packageName = "slash";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slash/-/slash-1.0.0.tgz";
        sha1 = "c41f2f6c39fc16d1cd17ad4b5d896114ae470d55";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-support-0.4.18" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.4.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.18.tgz";
        sha512 = "try0/JqxPLF9nOjvSta7tVondkP5dwgyLDjVoyMDlmjugT2lRZ1OfsrYTkCd2hkDnJTKRbO/Rl3orm8vlsUzbA==";
      };
    };
    "stream-browserify-2.0.2" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-2.0.2.tgz";
        sha512 = "nX6hmklHs/gr2FuxYDltq8fJA1GDlxKQCz8O/IM4atRqBH8OORmBNgfvW5gG10GT/qQ9u0CzIvr2X5Pkt6ntqg==";
      };
    };
    "stream-combiner2-1.1.1" = {
      name = "stream-combiner2";
      packageName = "stream-combiner2";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.1.1.tgz";
        sha1 = "fb4d8a1420ea362764e21ad4780397bebcb41cbe";
      };
    };
    "stream-http-2.8.3" = {
      name = "stream-http";
      packageName = "stream-http";
      version = "2.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-http/-/stream-http-2.8.3.tgz";
        sha512 = "+TSkfINHDo4J+ZobQLWiMouQYB+UVYFttRA94FpEzzJ7ZdqcL4uUUQ7WkdkI4DSozGmgBUE/a47L+38PenXhUw==";
      };
    };
    "stream-splicer-2.0.1" = {
      name = "stream-splicer";
      packageName = "stream-splicer";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-splicer/-/stream-splicer-2.0.1.tgz";
        sha512 = "Xizh4/NPuYSyAXyT7g8IvdJ9HJpxIGL9PjyhtywCZvvP0OPIdqyrr4dMikeuvY8xahpdKEBlBTySe583totajg==";
      };
    };
    "string.prototype.trimend-1.0.1" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.1.tgz";
        sha512 = "LRPxFUaTtpqYsTeNKaFOw3R4bxIzWOnbQ837QfBylo8jIxtcbK/A/sMV7Q+OAV/vWo+7s25pOE10KYSjaSO06g==";
      };
    };
    "string.prototype.trimleft-2.1.2" = {
      name = "string.prototype.trimleft";
      packageName = "string.prototype.trimleft";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.1.2.tgz";
        sha512 = "gCA0tza1JBvqr3bfAIFJGqfdRTyPae82+KTnm3coDXkZN9wnuW3HjGgN386D7hfv5CHQYCI022/rJPVlqXyHSw==";
      };
    };
    "string.prototype.trimright-2.1.2" = {
      name = "string.prototype.trimright";
      packageName = "string.prototype.trimright";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.1.2.tgz";
        sha512 = "ZNRQ7sY3KroTaYjRS6EbNiiHrOkjihL9aQE/8gfQ4DtAC/aEBRHFJa44OmoWxGGqXuJlfKkZW4WcXErGr+9ZFg==";
      };
    };
    "string.prototype.trimstart-1.0.1" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.1.tgz";
        sha512 = "XxZn+QpvrBI1FOcg6dIpxUPgWCPuNXvMD72aaRaUQv1eD4e/Qy8i/hFTe0BUmD60p/QA6bh1avmuPTfNjqVWRw==";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "subarg-1.0.0" = {
      name = "subarg";
      packageName = "subarg";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/subarg/-/subarg-1.0.0.tgz";
        sha1 = "f62cf17581e996b48fc965699f54c06ae268b8d2";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "syntax-error-1.4.0" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/syntax-error/-/syntax-error-1.4.0.tgz";
        sha512 = "YPPlu67mdnHGTup2A8ff7BC2Pjq0e0Yp/IyTFN03zWO0RcK07uLcbi7C2KpGR2FvWbaB0+bfE27a+sBKebSo7w==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "through2-2.0.5" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.5.tgz";
        sha512 = "/mrRod8xqpA+IHSLyGCQ2s8SPHiCDEeQJSep1jqLYeEUClOFG2Qsh+4FU6G9VeqpZnGW/Su8LQGc4YKni5rYSQ==";
      };
    };
    "timers-browserify-1.4.2" = {
      name = "timers-browserify";
      packageName = "timers-browserify";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz";
        sha1 = "c9c58b575be8407375cb5e2462dacee74359f41d";
      };
    };
    "to-arraybuffer-1.0.1" = {
      name = "to-arraybuffer";
      packageName = "to-arraybuffer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-arraybuffer/-/to-arraybuffer-1.0.1.tgz";
        sha1 = "7d229b1fcc637e466ca081180836a7aabff83f43";
      };
    };
    "to-fast-properties-1.0.3" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-1.0.3.tgz";
        sha1 = "b83571fa4d8c25b82e231b06e3a3055de4ca1a47";
      };
    };
    "trim-right-1.0.1" = {
      name = "trim-right";
      packageName = "trim-right";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-right/-/trim-right-1.0.1.tgz";
        sha1 = "cb2e1203067e0c8de1f614094b9fe45704ea6003";
      };
    };
    "tty-browserify-0.0.1" = {
      name = "tty-browserify";
      packageName = "tty-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.1.tgz";
        sha512 = "C3TaO7K81YvjCgQH9Q1S3R3P3BtN3RIM8n+OvX4il1K1zgE8ZhI0op7kClgkxtutIE8hQrcrHBXvIheqKUUCxw==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "umd-3.0.3" = {
      name = "umd";
      packageName = "umd";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-3.0.3.tgz";
        sha512 = "4IcGSufhFshvLNcMCV80UnQVlZ5pMOC8mvNPForqwA4+lzYQuetTESLDQkeLmihq8bRcnpbQa48Wb8Lh16/xow==";
      };
    };
    "undeclared-identifiers-1.1.3" = {
      name = "undeclared-identifiers";
      packageName = "undeclared-identifiers";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/undeclared-identifiers/-/undeclared-identifiers-1.1.3.tgz";
        sha512 = "pJOW4nxjlmfwKApE4zvxLScM/njmwj/DiUBv7EabwE4O8kRUy+HIwxQtZLBPll/jx1LJyBcqNfB3/cpv9EZwOw==";
      };
    };
    "url-0.11.0" = {
      name = "url";
      packageName = "url";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.11.0.tgz";
        sha1 = "3838e97cfc60521eb73c525a8e55bfdd9e2e28f1";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "util-0.10.4" = {
      name = "util";
      packageName = "util";
      version = "0.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.4.tgz";
        sha512 = "0Pm9hTQ3se5ll1XihRic3FDIku70C+iHUdT/W926rSgHV5QgXsYbKZN8MSC3tJtSkhuROzvsQjAaFENRXr+19A==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "vm-browserify-0.0.4" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.4.tgz";
        sha1 = "5d7ea45bbef9e4a6ff65f95438e0a87c357d5a73";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
  args = {
    name = "ghc-perf-import";
    packageName = "ghc-perf-import";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."JSONStream-1.3.5"
      sources."acorn-7.2.0"
      sources."acorn-node-1.8.2"
      sources."acorn-walk-7.1.1"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      (sources."asn1.js-4.10.1" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      (sources."assert-1.5.0" // {
        dependencies = [
          sources."inherits-2.0.1"
          sources."util-0.10.3"
        ];
      })
      sources."babel-code-frame-6.26.0"
      sources."babel-core-6.26.3"
      (sources."babel-generator-6.26.1" // {
        dependencies = [
          sources."jsesc-1.3.0"
        ];
      })
      sources."babel-helper-call-delegate-6.24.1"
      sources."babel-helper-define-map-6.26.0"
      sources."babel-helper-function-name-6.24.1"
      sources."babel-helper-get-function-arity-6.24.1"
      sources."babel-helper-hoist-variables-6.24.1"
      sources."babel-helper-optimise-call-expression-6.24.1"
      sources."babel-helper-regex-6.26.0"
      sources."babel-helper-replace-supers-6.24.1"
      sources."babel-helpers-6.24.1"
      sources."babel-messages-6.23.0"
      sources."babel-plugin-check-es2015-constants-6.22.0"
      sources."babel-plugin-transform-es2015-arrow-functions-6.22.0"
      sources."babel-plugin-transform-es2015-block-scoped-functions-6.22.0"
      sources."babel-plugin-transform-es2015-block-scoping-6.26.0"
      sources."babel-plugin-transform-es2015-classes-6.24.1"
      sources."babel-plugin-transform-es2015-computed-properties-6.24.1"
      sources."babel-plugin-transform-es2015-destructuring-6.23.0"
      sources."babel-plugin-transform-es2015-duplicate-keys-6.24.1"
      sources."babel-plugin-transform-es2015-for-of-6.23.0"
      sources."babel-plugin-transform-es2015-function-name-6.24.1"
      sources."babel-plugin-transform-es2015-literals-6.22.0"
      sources."babel-plugin-transform-es2015-modules-amd-6.24.1"
      sources."babel-plugin-transform-es2015-modules-commonjs-6.26.2"
      sources."babel-plugin-transform-es2015-modules-systemjs-6.24.1"
      sources."babel-plugin-transform-es2015-modules-umd-6.24.1"
      sources."babel-plugin-transform-es2015-object-super-6.24.1"
      sources."babel-plugin-transform-es2015-parameters-6.24.1"
      sources."babel-plugin-transform-es2015-shorthand-properties-6.24.1"
      sources."babel-plugin-transform-es2015-spread-6.22.0"
      sources."babel-plugin-transform-es2015-sticky-regex-6.24.1"
      sources."babel-plugin-transform-es2015-template-literals-6.22.0"
      sources."babel-plugin-transform-es2015-typeof-symbol-6.23.0"
      sources."babel-plugin-transform-es2015-unicode-regex-6.24.1"
      sources."babel-plugin-transform-regenerator-6.26.0"
      sources."babel-plugin-transform-strict-mode-6.24.1"
      sources."babel-preset-es2015-6.24.1"
      sources."babel-register-6.26.0"
      sources."babel-runtime-6.26.0"
      sources."babel-template-6.26.0"
      sources."babel-traverse-6.26.0"
      sources."babel-types-6.26.0"
      sources."babelify-7.3.0"
      sources."babylon-6.18.0"
      sources."balanced-match-1.0.0"
      sources."base64-js-1.3.1"
      sources."bn.js-5.1.2"
      sources."brace-expansion-1.1.11"
      sources."brorand-1.1.0"
      sources."browser-pack-6.1.0"
      (sources."browser-resolve-1.11.3" // {
        dependencies = [
          sources."resolve-1.1.7"
        ];
      })
      sources."browserify-13.3.0"
      sources."browserify-aes-1.2.0"
      sources."browserify-cipher-1.0.1"
      sources."browserify-des-1.0.2"
      (sources."browserify-rsa-4.0.1" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      (sources."browserify-sign-4.2.0" // {
        dependencies = [
          sources."readable-stream-3.6.0"
          sources."safe-buffer-5.2.1"
          sources."string_decoder-1.3.0"
        ];
      })
      sources."browserify-zlib-0.1.4"
      sources."buffer-4.9.2"
      sources."buffer-from-1.1.1"
      sources."buffer-xor-1.0.3"
      sources."builtin-status-codes-3.0.0"
      sources."cached-path-relative-1.0.2"
      sources."chalk-1.1.3"
      sources."cipher-base-1.0.4"
      (sources."combine-source-map-0.8.0" // {
        dependencies = [
          sources."convert-source-map-1.1.3"
        ];
      })
      sources."concat-map-0.0.1"
      (sources."concat-stream-1.5.2" // {
        dependencies = [
          sources."readable-stream-2.0.6"
        ];
      })
      sources."console-browserify-1.2.0"
      sources."constants-browserify-1.0.0"
      sources."convert-source-map-1.7.0"
      sources."core-js-2.6.11"
      sources."core-util-is-1.0.2"
      (sources."create-ecdh-4.0.3" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."crypto-browserify-3.12.0"
      sources."dash-ast-1.0.0"
      sources."debug-2.6.9"
      sources."define-properties-1.1.3"
      sources."defined-1.0.0"
      sources."deps-sort-2.0.1"
      sources."des.js-1.0.1"
      sources."detect-indent-4.0.0"
      (sources."detective-4.7.1" // {
        dependencies = [
          sources."acorn-5.7.4"
        ];
      })
      (sources."diffie-hellman-5.0.3" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."domain-browser-1.1.7"
      sources."duplexer2-0.1.4"
      (sources."elliptic-6.5.2" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."es-abstract-1.17.5"
      sources."es-to-primitive-1.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."esutils-2.0.3"
      sources."events-1.1.1"
      sources."evp_bytestokey-1.0.3"
      sources."fast-safe-stringify-2.0.7"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."get-assigned-identifiers-1.2.0"
      sources."glob-7.1.6"
      sources."globals-9.18.0"
      sources."has-1.0.3"
      sources."has-ansi-2.0.0"
      sources."has-symbols-1.0.1"
      (sources."hash-base-3.1.0" // {
        dependencies = [
          sources."readable-stream-3.6.0"
          sources."safe-buffer-5.2.1"
          sources."string_decoder-1.3.0"
        ];
      })
      sources."hash.js-1.1.7"
      sources."hmac-drbg-1.0.1"
      sources."home-or-tmp-2.0.0"
      sources."htmlescape-1.1.1"
      sources."https-browserify-0.0.1"
      sources."ieee754-1.1.13"
      sources."indexof-0.0.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."inline-source-map-0.6.2"
      (sources."insert-module-globals-7.2.0" // {
        dependencies = [
          sources."concat-stream-1.6.2"
        ];
      })
      sources."invariant-2.2.4"
      sources."is-buffer-1.1.6"
      sources."is-callable-1.1.5"
      sources."is-date-object-1.0.2"
      sources."is-finite-1.1.0"
      sources."is-regex-1.0.5"
      sources."is-symbol-1.0.3"
      sources."isarray-1.0.0"
      sources."js-tokens-3.0.2"
      sources."jsesc-0.5.0"
      sources."json-stable-stringify-0.0.1"
      sources."json5-0.5.1"
      sources."jsonify-0.0.0"
      sources."jsonparse-1.3.1"
      sources."labeled-stream-splicer-2.0.2"
      sources."lodash-4.17.15"
      sources."lodash.memoize-3.0.4"
      sources."loose-envify-1.4.0"
      sources."md5.js-1.3.5"
      (sources."miller-rabin-4.0.1" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."minimalistic-assert-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."mkdirp-0.5.5"
      sources."module-deps-4.1.1"
      sources."moment-2.26.0"
      sources."ms-2.0.0"
      sources."object-assign-4.1.1"
      sources."object-inspect-1.7.0"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.0"
      sources."object.entries-1.1.2"
      sources."object.values-1.1.1"
      sources."once-1.4.0"
      sources."os-browserify-0.1.2"
      sources."os-homedir-1.0.2"
      sources."os-tmpdir-1.0.2"
      sources."pako-0.2.9"
      sources."parents-1.0.1"
      sources."parse-asn1-5.1.5"
      sources."path-browserify-0.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."path-platform-0.11.15"
      sources."pbkdf2-3.0.17"
      sources."private-0.1.8"
      sources."process-0.11.10"
      sources."process-nextick-args-1.0.7"
      (sources."public-encrypt-4.0.3" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."punycode-1.4.1"
      sources."querystring-0.2.0"
      sources."querystring-es3-0.2.1"
      sources."randombytes-2.1.0"
      sources."randomfill-1.0.4"
      sources."read-only-stream-2.0.0"
      (sources."readable-stream-2.3.7" // {
        dependencies = [
          sources."process-nextick-args-2.0.1"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."regenerate-1.4.0"
      sources."regenerator-runtime-0.11.1"
      sources."regenerator-transform-0.10.1"
      sources."regexpu-core-2.0.0"
      sources."regjsgen-0.2.0"
      sources."regjsparser-0.1.5"
      sources."repeating-2.0.1"
      sources."resolve-1.17.0"
      sources."ripemd160-2.0.2"
      sources."safe-buffer-5.1.2"
      sources."sha.js-2.4.11"
      sources."shasum-1.0.2"
      sources."shasum-object-1.0.0"
      sources."shell-quote-1.7.2"
      sources."simple-concat-1.0.0"
      sources."slash-1.0.0"
      sources."source-map-0.5.7"
      sources."source-map-support-0.4.18"
      sources."stream-browserify-2.0.2"
      sources."stream-combiner2-1.1.1"
      sources."stream-http-2.8.3"
      sources."stream-splicer-2.0.1"
      sources."string.prototype.trimend-1.0.1"
      sources."string.prototype.trimleft-2.1.2"
      sources."string.prototype.trimright-2.1.2"
      sources."string.prototype.trimstart-1.0.1"
      sources."string_decoder-0.10.31"
      sources."strip-ansi-3.0.1"
      sources."subarg-1.0.0"
      sources."supports-color-2.0.0"
      sources."syntax-error-1.4.0"
      sources."through-2.3.8"
      sources."through2-2.0.5"
      sources."timers-browserify-1.4.2"
      sources."to-arraybuffer-1.0.1"
      sources."to-fast-properties-1.0.3"
      sources."trim-right-1.0.1"
      sources."tty-browserify-0.0.1"
      sources."typedarray-0.0.6"
      sources."umd-3.0.3"
      sources."undeclared-identifiers-1.1.3"
      (sources."url-0.11.0" // {
        dependencies = [
          sources."punycode-1.3.2"
        ];
      })
      (sources."util-0.10.4" // {
        dependencies = [
          sources."inherits-2.0.3"
        ];
      })
      sources."util-deprecate-1.0.2"
      sources."vm-browserify-0.0.4"
      sources."wrappy-1.0.2"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}